# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 20:46
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0002_seminar_speaker_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seminar',
            old_name='last_updated',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='seminarcancelannouncement',
            old_name='last_updated',
            new_name='modified',
        ),
        migrations.AlterField(
            model_name='seminar',
            name='location',
            field=models.ForeignKey(help_text='\'If you require a location not in the list,\nplease contact <a href="mailto:math-reports@stats.umanitoba.ca">web admins</a>', on_delete=django.db.models.deletion.CASCADE, to='places.ClassRoom'),
        ),
    ]
