# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 20:49
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0003_auto_20160621_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 21, 20, 49, 5, 455061, tzinfo=utc), verbose_name='creation time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminarcancelannouncement',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 21, 20, 49, 12, 947243, tzinfo=utc), verbose_name='creation time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seminar',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modification time'),
        ),
        migrations.AlterField(
            model_name='seminarcancelannouncement',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modification time'),
        ),
    ]
