# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 16:01
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0005_auto_20160621_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modification time')),
                ('verbose_name', models.CharField(help_text='Name of this seminar series', max_length=100, verbose_name='name')),
                ('slug', models.SlugField(help_text='A url fragment which uniquely identifies this seminar series', max_length=100, unique=True, verbose_name='URL fragment')),
                ('default_dayofweek', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')], help_text='The day of the week this seminar series normally occurs', verbose_name='usual day')),
                ('default_interval', models.PositiveSmallIntegerField(choices=[(1, 'Every week'), (2, 'Every 2 weeks'), (3, 'Every 3 weeks')], help_text='The seminar series normally occurs this often', verbose_name='usual occurance')),
                ('default_time', models.TimeField(help_text='The usual time seminars begin (use 24-hour time)', verbose_name='usual time')),
                ('description', models.TextField(blank=True, help_text='This will be processed as\n<a href="http://docutils.sourceforge.net/docs/user/rst/quickref.html" target="_blank">\nReStructuredText</a>.')),
                ('default_location', models.ForeignKey(help_text='The usual location for this seminars series', on_delete=django.db.models.deletion.CASCADE, to='places.ClassRoom', verbose_name='usual location')),
                ('organizer', models.ForeignKey(help_text='User group that is in charge of this seminar series (should have add, change, delete permissions for seminars)', on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='organizing group')),
            ],
            options={
                'ordering': ['verbose_name'],
                'verbose_name': 'series',
                'verbose_name_plural': 'series',
            },
        ),
    ]
