# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 16:36
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0006_seminarseries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarseries',
            name='organizer',
            field=models.ForeignKey(help_text='User group that is in charge of this seminar series (should have add, change, delete permissions for seminars)', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='organizing group'),
        ),
    ]
