# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 18:24
from __future__ import unicode_literals

from django.db import migrations

from .. import conf


def forward_data(apps, schema_editor):
    # We can't import the  model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    
    model = apps.get_model("seminars", "SeminarSeries")
    location_model = apps.get_model(*conf.get('location:model').split('.'))
    try:
        default_location = location_model.objects.get(slug='tba')  # this *should* exist...
    except location_model.DoesNotExist:
        return  # do nothing in this case.

    # ... but it doesn't always, especially with a new db.

    # create a default seminar series, if one doesn't already exist;
    # this will provide a default value for the series foreign key
    # relationship on seminars.
    
    model.objects.get_or_create(slug='general',
                defaults={'verbose_name': 'General',
                          'default_dayofweek': 4,
                          'default_interval': 0,
                          'default_time': '14:30:00',
                          'default_location': default_location
                          })
    


def backward_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0007_auto_20160622_1136'),
    ]

    operations = [
        migrations.RunPython(forward_data, backward_data),
    ]
