# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 20:44
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0008_auto_20160622_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='series',
            field=models.ForeignKey(help_text='Which seminar series this belongs to', on_delete=django.db.models.deletion.CASCADE, null=True, to='seminars.SeminarSeries', verbose_name='seminar series'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seminarseries',
            name='default_interval',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Irregular'), (1, 'Every week'), (2, 'Every 2 weeks'), (3, 'Every 3 weeks')], help_text='The seminar series normally occurs this often', verbose_name='usual occurance'),
        ),
        migrations.AlterField(
            model_name='seminarseries',
            name='organizer',
            field=models.ForeignKey(blank=True, help_text='User group that is in charge of this seminar series (should have add, change, delete permissions for seminars)', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='organizing group'),
        ),
        
    ]
