# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 20:44
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0009_2_auto_20160622_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='series',
            field=models.ForeignKey(help_text='Which seminar series this belongs to', on_delete=django.db.models.deletion.CASCADE, to='seminars.SeminarSeries', verbose_name='seminar series'),
            preserve_default=False,
        ),
        
    ]
