# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0011_auto_20160623_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='affiliation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique_for_date='when'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='speaker',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
