# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0013_auto_20160623_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarseries',
            name='show_seminars',
            field=models.BooleanField(default=True, help_text='Seminars from this series will be included in all lists and advertising (as long as the speaker is set)', verbose_name='show seminars in main archive'),
        ),
        migrations.AddField(
            model_name='seminarseries',
            name='show_series',
            field=models.BooleanField(default=True, help_text='This series will show in the list of series', verbose_name='show series in series list'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='abstract',
            field=models.TextField(blank=True, help_text='The text of  abstract. This will be processed as\n<a href="http://docutils.sourceforge.net/docs/user/rst/quickref.html" target="_blank">\nReStructuredText</a>.', verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='abstract_url',
            field=models.URLField(blank=True, help_text='An optional link to the talk abstract', verbose_name='abstract_url'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='active',
            field=models.BooleanField(default=True, help_text='Uncheck this to remove without deleting'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='affiliation',
            field=models.CharField(blank=True, help_text="The speaker's home institution or department (recommended)", max_length=150, verbose_name='affiliation'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='note',
            field=models.CharField(blank=True, help_text='An optional additional note for advertising (e.g., coffee)', max_length=200, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='slug',
            field=models.SlugField(blank=True, help_text='A url fragment which uniquely identifies this seminar', max_length=200, verbose_name='URL fragment'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='speaker',
            field=models.CharField(blank=True, help_text='Who is giving the talk', max_length=100, verbose_name='speaker'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='speaker_url',
            field=models.URLField(blank=True, help_text="An optional link to the speaker's website", verbose_name="speaker's url"),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='title',
            field=models.CharField(blank=True, help_text='The title of the talk', max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='when',
            field=models.DateTimeField(help_text='When the seminar begins', verbose_name='date and time'),
        ),
        migrations.AlterField(
            model_name='seminarcancelannouncement',
            name='active',
            field=models.BooleanField(default=True, help_text='Uncheck this to remove without deleting'),
        ),
        migrations.AlterField(
            model_name='seminarseries',
            name='active',
            field=models.BooleanField(default=True, help_text='Uncheck this to remove without deleting'),
        ),
        migrations.AlterField(
            model_name='seminarseries',
            name='default_interval',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Irregular'), (7, 'Every week'), (14, 'Every 2 weeks'), (21, 'Every 3 weeks')], help_text='The seminar series normally occurs this often', verbose_name='usual occurance'),
        ),
    ]
