# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-28 20:55
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0015_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarseries',
            name='descriptor',
            field=models.CharField(default='', help_text='A term that describes a single event in this series (such as: "lecture", "talk" or "seminar") [use lower case]', max_length=32, verbose_name='descriptor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminarseries',
            name='descriptor_plural',
            field=models.CharField(default='', help_text='A term that describes multile events in this series (plural of above)', max_length=32, verbose_name='plural descriptor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminarseries',
            name='short_name',
            field=models.CharField(default='', help_text='A short name for this seminar series (do not include the descriptor, below)', max_length=100, verbose_name='short name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seminar',
            name='abstract_url',
            field=models.URLField(blank=True, help_text='An optional link to the talk abstract', verbose_name='abstract url'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='location',
            field=models.ForeignKey(help_text='\'If you require a location not in the list,\nplease contact <a href="mailto:www@stats.umanitoba.ca">Dave Gabrielson</a>', on_delete=django.db.models.deletion.CASCADE, to='places.ClassRoom'),
        ),
        migrations.AlterField(
            model_name='seminarseries',
            name='verbose_name',
            field=models.CharField(help_text='Title of this seminar series', max_length=100, verbose_name='name'),
        ),
    ]
