# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-31 16:05
from __future__ import unicode_literals

from django.db import migrations


def forward_data(apps, schema_editor):
    model = apps.get_model("seminars", "SeminarSeries")
    for series in model.objects.all():
        if not series.short_name:
            series.short_name = series.verbose_name
        if not series.descriptor:
            series.descriptor = 'seminar'
        if not series.descriptor_plural:
            series.descriptor_plural = 'seminars'
        series.save()
        

def backward_data(apps, schema_editor):
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0016_auto_20161028_1555'),
    ]

    operations = [
         migrations.RunPython(forward_data, backward_data),
    ]
