# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 20:52
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations

import seminars.conf


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0018_auto_20161031_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, help_text='A url fragment which uniquely identifies this seminar', max_length=200, populate_from=seminars.conf.seminar_slugify, unique_with=('when',), verbose_name='URL fragment'),
        ),
        migrations.AlterField(
            model_name='seminarseries',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, help_text='A url fragment which uniquely identifies this seminar series', max_length=100, populate_from='short_name', unique=True, verbose_name='URL fragment'),
        ),
    ]
