# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 15:54
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0019_auto_20170109_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='location',
            field=models.ForeignKey(help_text='\'If you require a location not in the list,\nplease contact <a href="mailto:www@stats.umanitoba.ca">Dave Gabrielson</a>', on_delete=django.db.models.deletion.PROTECT, to='places.ClassRoom'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='series',
            field=models.ForeignKey(help_text='Which seminar series this belongs to', on_delete=django.db.models.deletion.PROTECT, to='seminars.SeminarSeries', verbose_name='seminar series'),
        ),
        migrations.AlterField(
            model_name='seminarseries',
            name='default_location',
            field=models.ForeignKey(help_text='The usual location for this seminars series', on_delete=django.db.models.deletion.PROTECT, to='places.ClassRoom', verbose_name='usual location'),
        ),
        migrations.AlterField(
            model_name='seminarseries',
            name='organizer',
            field=models.ForeignKey(blank=True, help_text='User group that is in charge of this seminar series (should have add, change, delete permissions for seminars)', null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.Group', verbose_name='organizing group'),
        ),
    ]
