# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 16:31
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0020_auto_20170602_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How long this seminar runs for (leave blank for default)', null=True, verbose_name='duration'),
        ),
        migrations.AddField(
            model_name='seminarseries',
            name='default_duration',
            field=models.PositiveSmallIntegerField(default=60, help_text='The usual number of minutes a seminar runs for', verbose_name='usual duration'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='location',
            field=models.ForeignKey(help_text="'If you require a location not in the list,\nplease contact the main office", on_delete=django.db.models.deletion.PROTECT, to='places.ClassRoom'),
        ),
        migrations.AlterField(
            model_name='seminarseries',
            name='description',
            field=models.TextField(blank=True, help_text='This will be processed as <a href="/rst/" target="_blank">ReStructuredText</a>'),
        ),
    ]
