# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0021_auto_20170922_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='affiliation',
            field=models.CharField(blank=True, help_text="The speaker's home institution or department (recommended)", max_length=250, verbose_name='affiliation'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How long this seminar runs for, in <strong>minutes</strong> (leave blank for default)', null=True, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='seminarseries',
            name='default_duration',
            field=models.PositiveSmallIntegerField(default=60, help_text='The usual number of <strong>minutes</strong> a seminar runs for', verbose_name='usual duration'),
        ),
    ]
